2022-11-29 21:01:03,560 - easytorch-training - INFO - Initializing training.
2022-11-29 21:01:03,560 - easytorch-training - INFO - Set clip grad, param: {'max_norm': 5.0}
2022-11-29 21:01:03,560 - easytorch-training - INFO - Building training data loader.
2022-11-29 21:01:03,741 - easytorch-training - INFO - Set optim: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.002
    maximize: False
    weight_decay: 0.0001
)
2022-11-29 21:01:03,742 - easytorch-training - INFO - Set lr_scheduler: <torch.optim.lr_scheduler.MultiStepLR object at 0x7fb34990ae90>
2022-11-29 21:01:04,907 - easytorch-training - INFO - Initializing validation.
2022-11-29 21:01:04,907 - easytorch-training - INFO - Building val data loader.
2022-11-29 21:01:05,266 - easytorch-training - INFO - Epoch 1 / 200
2022-11-29 21:01:06,021 - easytorch-training - ERROR - Traceback (most recent call last):
  File "/home/cseadmin/ght/anaconda3/envs/ght/lib/python3.7/site-packages/easytorch/launcher/launcher.py", line 52, in training_func
    runner.train(cfg)
  File "/home/cseadmin/ght/anaconda3/envs/ght/lib/python3.7/site-packages/easytorch/core/runner.py", line 351, in train
    loss = self.train_iters(epoch, iter_index, data)
  File "/home/cseadmin/ght/BasicTS/basicts/runners/base_tsf_runner.py", line 237, in train_iters
    forward_return = list(self.forward(data=data, epoch=epoch, iter_num=iter_num, train=True))
  File "/home/cseadmin/ght/BasicTS/basicts/runners/runner_zoo/simple_tsf_runner.py", line 67, in forward
    prediction_data = self.model(history_data=history_data, future_data=future_data_4_dec, batch_seen=iter_num, epoch=epoch, train=train)
  File "/home/cseadmin/ght/anaconda3/envs/ght/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cseadmin/ght/BasicTS/basicts/archs/arch_zoo/gwnet_arch/gwnet_arch.py", line 200, in forward
    gate = self.gate_convs[i](residual)
  File "/home/cseadmin/ght/anaconda3/envs/ght/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cseadmin/ght/anaconda3/envs/ght/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/cseadmin/ght/anaconda3/envs/ght/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 299, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [64, 32, 307, 13]

